# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCXDhGZ7aXcu-lsW5ZBba1myIHofCbpk
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 6])
y = np.array([0, 250])

plt.plot(x, y)
plt.show()

x = np.array([1, 2, 6, 8])
y = np.array([3, 8, 1, 10])

plt.plot(x, y)
plt.show()

y = np.array([3, 8, 1, 10])

plt.plot(y, marker = 'X')
plt.show()

y = np.array([3, 8, 1, 10])

plt.plot(y, 'X:r')
plt.show()

y = np.array([3, 8, 1, 10])

plt.plot(y, marker = 'X', ms = 20)
plt.show()

x = np.array([45, 20, 20, 15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(x, labels = mylabels, startangle = 90)
plt.show()